services:

  mysql:
    image: mysql:8.0
    container_name: mysql_for_webserver
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: usersdb
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 10

  database-server:
    build: ./DatabaseServer
    container_name: database_server
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      mysql:
        condition: service_healthy
