FROM eclipse-temurin:17-jdk-alpine

COPY /target/DatabaseServer-1.0-SNAPSHOT.jar /app/DatabaseServer.jar

ENTRYPOINT ["java", "--add-opens", "java.base/java.lang=ALL-UNNAMED", "-jar", "/app/DatabaseServer.jar"]