apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: webserver
data:
  POSTGRES_HOST: postgres-service
  KAFKA_BOOTSTRAP_SERVERS: kafka-service:9092
  AUTH_SERVICE_URL: http://auth-service:8083/api/auth/validate/
  REDIS_HOST: redis-service
  ZIPKIN_ENDPOINT: http://zipkin-service:9411/api/v2/spans
