
package soapclient;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "DataProcessor", targetNamespace = "http://soapWebService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DataProcessor {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "decodeAndStore", targetNamespace = "http://soapWebService/", className = "soapclient.DecodeAndStore")
    @ResponseWrapper(localName = "decodeAndStoreResponse", targetNamespace = "http://soapWebService/", className = "soapclient.DecodeAndStoreResponse")
    @Action(input = "http://soapWebService/DataProcessor/decodeAndStoreRequest", output = "http://soapWebService/DataProcessor/decodeAndStoreResponse")
    public String decodeAndStore(
        @WebParam(name = "arg0", targetNamespace = "")
        Person arg0);

    /**
     * 
     * @return
     *     returns java.util.List<soapclient.Person>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPersons", targetNamespace = "http://soapWebService/", className = "soapclient.GetPersons")
    @ResponseWrapper(localName = "getPersonsResponse", targetNamespace = "http://soapWebService/", className = "soapclient.GetPersonsResponse")
    @Action(input = "http://soapWebService/DataProcessor/getPersonsRequest", output = "http://soapWebService/DataProcessor/getPersonsResponse")
    public List<Person> getPersons();

}
