
package soapclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "DataProcessorImplService", targetNamespace = "http://soapWebService/", wsdlLocation = "http://database-server:8081/ws/decoder?wsdl")
public class DataProcessorImplService
    extends Service
{

    private final static URL DATAPROCESSORIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException DATAPROCESSORIMPLSERVICE_EXCEPTION;
    private final static QName DATAPROCESSORIMPLSERVICE_QNAME = new QName("http://soapWebService/", "DataProcessorImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://database-server:8081/ws/decoder?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DATAPROCESSORIMPLSERVICE_WSDL_LOCATION = url;
        DATAPROCESSORIMPLSERVICE_EXCEPTION = e;
    }

    public DataProcessorImplService() {
        super(__getWsdlLocation(), DATAPROCESSORIMPLSERVICE_QNAME);
    }

    public DataProcessorImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DATAPROCESSORIMPLSERVICE_QNAME, features);
    }

    public DataProcessorImplService(URL wsdlLocation) {
        super(wsdlLocation, DATAPROCESSORIMPLSERVICE_QNAME);
    }

    public DataProcessorImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DATAPROCESSORIMPLSERVICE_QNAME, features);
    }

    public DataProcessorImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DataProcessorImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DataProcessor
     */
    @WebEndpoint(name = "DataProcessorImplPort")
    public DataProcessor getDataProcessorImplPort() {
        return super.getPort(new QName("http://soapWebService/", "DataProcessorImplPort"), DataProcessor.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DataProcessor
     */
    @WebEndpoint(name = "DataProcessorImplPort")
    public DataProcessor getDataProcessorImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soapWebService/", "DataProcessorImplPort"), DataProcessor.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DATAPROCESSORIMPLSERVICE_EXCEPTION!= null) {
            throw DATAPROCESSORIMPLSERVICE_EXCEPTION;
        }
        return DATAPROCESSORIMPLSERVICE_WSDL_LOCATION;
    }

}
