# 1. SZAKASZ: Építés (Build)
FROM node:18-alpine AS build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# 2. SZAKASZ: Futtatás (Production)
FROM nginx:stable-alpine
# Másoljuk a lefordított statikus fájlokat az Nginx könyvtárába
COPY --from=build-stage /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]