services:
  mysql_for_webserver:
    image: mysql:8.0
    container_name: mysql_for_webserver
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
  userinput-server:
    build:
      context: ../
      dockerfile: docker/Dockerfile_UserInputServer
    image: userinput:latest
    depends_on:
      - database-server
    ports:
      - "8080:8080"
    volumes:
      - ../UserInputServer/src/main/webapp/jsDevelopment:/usr/local/tomcat/webapps/jsDevelopment
  database-server:
    build:
      context: ../
      dockerfile: docker/Dockerfile_DatabaseServer
    image: database:latest
    depends_on:
      mysql_for_webserver:
        condition: service_healthy
    ports:
      - "8081:8081"
