apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: auth-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/authdb
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: webserver
spec:
  selector:
    app: auth-service
  ports:
    - port: 8083
      targetPort: 8083
