CREATE DATABASE IF NOT EXISTS usersdb CHARACTER SET utf8 COLLATE utf8_general_ci;

USE usersdb;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100),
    birthDay DATE,
    city VARCHAR(100)
    );