server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: "http://auth-service:8083"
          predicates:
            - Path=/api/auth/**

        - id: database-server
          uri: "http://database-server:8080"
          predicates:
            - Path=/api/**

management:
  endpoints:
    web:
      exposure:
        include: health
